### ISSUE TITLE
description not uploaded?

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/rac-extract-payload#114]
rac -description protocol.txt -project nadir-tests -aws RacFiles/MyArchive1_20200527-075857_20200527-080911.rac

when I run this I cannot see any description uploaded to AWS

text file looks like this:

## NADIR CAMERA FUNCTIONAL TEST
27/05/2020
Björn & Linda

RacFile should contain 

1 image with CCDSEL 1, WDW 7
1 image with CCDSEL 64, WDW 7
1 image with CCDSEL 64, WDW 4
1 image with CCDSEL 64, WDW 7

**Comment by local-minimum** [comment]
yes. The description file always gets renamed but keeps the extension so yours becomes `ABOUT.txt` and is in https://s3.console.aws.amazon.com/s3/object/mats-l0-artifacts/nadir-tests/ABOUT.txt?region=eu-north-1&tab=overview

**Comment by OleMartinChristensen** [comment]
ok found it now
