### ISSUE TITLE
SPH package type is conflicted

### ISSUE THREAD

**Issue by local-minimum** [innosat-mats/rac-extract-payload#12]
From the python code:
```
    packet['SPH_type'] = int(A_bin[0][3],2)
    if packet['SPH_type'] == 0:
        packet['SPH_type_mnemonic'] = 'TM'
    elif packet['SPH_type'] == 1:
        packet['SPH_type_mnemonic'] = 'TC'
```

Our rac files seem to indicate wrong package type sometimes.

Ask @OleMartinChristensen  to produce proper files or for the spec to be updated.

**Comment by OleMartinChristensen** [comment]
Do you get another number that 0 or 1? Or is it that you sometimes get TC packets?

**Comment by local-minimum** [comment]
In the rac files we got, I think they only have TC packages, or so it would seem, if we disregard the type and parse it as TM packages we can read the content fine, at least that was as far as I understood @joakimmoller

**Comment by OleMartinChristensen** [comment]
ok, lets to a telecon on it when you guys want, show me some examples.

**Comment by joakimmoller** [comment]
in "source package header" the "Type" is always 0 which means it should be TC-packages in the payload. But there is mainly TM-packages in the payload (type should be 1), but some TC-packages also exists but it is hard to distinguish between them (without workarounds).

**Comment by joakimmoller** [comment]
I'll prepare some stats from the files we have - then we talk on Monday.

**Comment by joakimmoller** [comment]
After receiving the new update of aez icd (issue h) this is not an issue. One of the differences from previous versions was the removal of some element in the HTR structure. Now we can process the housekeeping data from the instrument. TC/TM flag on packages was a "typo". There are only TM-packages in the files.
