### ISSUE TITLE
documentation of new parameter names

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/rac-extract-payload#120]
Jag sitter och uppdaterar mina scripts så att de ska vara kompatibla med den nya rac outputen. Det är några variabler som jag inte vet var de finns (markerade i rött i den bifogade filen) och sen finns de några jag kan gissa vad de är (markerade i organge) och några som heter likadant (markerad i grönt). Skulle ni kunna fylla i de röda och kolla de oranga så att vi får detta korrekt och dokumenterat?  
[OldToNewRacFileParameters.docx](https://github.com/innosat-mats/rac-extract-payload/files/4728785/OldToNewRacFileParameters.docx)

**Comment by local-minimum** [comment]
Jag kollade lite snabbt, kanske @skymandr  eller @joakimmoller kan kolla sa jag inte vänt på några bits, men principen är att all data som finns i specen är inkluderad och avläst så som den beskrivs i specen:
* "SID_mnemoic" är nu kolumnerna SID och RID beroende på om det är en SID eller RID
* EXPTS & EXPTSS finns nu som datum eller nanosekunder beroende på vad som är trevligast att använda.
* Komplexa parametrar som WDW, NCBIN, GAIN rapporteras ut som sina komponenter efter specifikationen.
* WDW Mode: Manual (0) / Automatic (1)
* WDW InputDataWindow: high..low (bits)
* Gain Mode: High (0) / Low (1)
* Gain Timing: Faster (0) /  Full (1)

**Comment by lindamegner** [comment]
OK, då kanske problemet bara var att jag inte har specen. Jag tyckte jag frågade Ole Martin om detta men måste ha missuppfattat att det inte fanns någon. Så var finns den (resten alltså  - förutom utdraget nedan) ?

Linda

**Comment by lindamegner** [comment]
Hej igen, 
I så fall tror jag jag har koll på allt förutom Signal mode och Gain mode.
Förut delades parametern GAINs bits upp i SigMode, DigGain och TimingFlag.
Nu verkar det som om det som förut hette SigMode nu heter Gain Mode, TimingFlag och heter GainTiming. Men vad har då  De 4 bitsen i DigGain hamnat?

**Comment by local-minimum** [comment]
Jag menade AEZ specen för innehållet i CCD Datan. Och du har rätt att de fyra truncation bitsen avkodas, men vi missade att få ut dem till csvn/json!

**Comment by local-minimum** [comment]
Jag skapade en specifik issue för det https://github.com/innosat-mats/rac-extract-payload/issues/121
