### ISSUE TITLE
NColBinFPGA has changed definition

### ISSUE THREAD

**Issue by lindamegner** [innosat-mats/rac-extract-payload#122]
Hej,
Enligt Software ICD (utklipp nedan om ni kan se det annars stycke 6.4.1 i ICDn) ska NColBinFPGA vara definierat som en exponent, så att 2 upphöjt till NColBinFPGA ska ge antalet FPGA binnade pixlar. Dvs om ingen binning har skett då ska antalet binnande pixlar vara 1 vilket betyder att NColBinFPGA ska vara 0.  Med den nya racextract verkar det dock som om NColBinFPGA, eller NCBIN FPGA Columns som den nu heter verkar jag få värdet 1 för obinnade. 

![image](https://user-images.githubusercontent.com/51697504/84017416-e7e8f980-a97e-11ea-826a-dcff7165f6c8.png)

**Comment by skymandr** [comment]
Det kanske dessutom är lite onödigt att den heter `NCBIN FPGA Columns` om `C` i `NCBIN` betyder columns. Samma, förmodar jag, för `NCBIN CCD Columns`.

**Comment by local-minimum** [comment]
Avsikten där var samma som för heater, att retunera det man antagligen är intresserad av, dvs antalet binnade pixlar istället för exponenten.

**Comment by lindamegner** [comment]
Jo , det är bra tänkt i och för sig. Men om vi ändrar sånt här måste vi ha det dokumenterat. Så antingen måste vi göra som det står i ICDn eller så måste vi dokumentera ändringarna på något bra vis. Vilket som funkar nog egentligen för oss.

Eller vad säger du Ole Martin?

Linda

**Comment by skymandr** [comment]
Som ett tillägg kan sägas att motiveringen, som jag minns det (rätta mig om jag har fel @local-minimum), är att det som hamnar i CSV först och främst är tänkt för L1-databasen snarare än L0. Jag håller givetvis med om att det måste dokumenteras.

**Comment by skymandr** [comment]
Ping @OleMartinChristensen

**Comment by OleMartinChristensen** [comment]
ja, vi kom frem till att all manipulation som är rent datateknisk bäst görs i första steget, så därför är det så. som linda säger behövs det nog bara en liten tabell som beskriver värdet, kanske med en tydig markering för de värden man har ändrat

**Comment by local-minimum** [comment]
Jag skapade en issue för det #123, så då kanske vi kan stänga den här?

**Comment by OleMartinChristensen** [comment]
ok, forstätter i issure #123
