### ISSUE TITLE
Problem extracting racfiles

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/rac-extract-payload#127]
rac --project from_xml from_xml_202010*.rac
2020/10/13 14:00:03 failed creating from_xml/from_xml_20201011-181721_20201011-201636_181459394989014_6.png: open from_xml/from_xml_20201011-181721_20201011-201636_181459394989014_6.png: too many open files
panic: open from_xml/from_xml_20201011-181721_20201011-201636_181459394989014_6.png: too many open files

goroutine 242600 [running]:
github.com/innosat-mats/rac-extract-payload/internal/exports.DiskCallbackFactory.func1.1(0xc0000b0b30, 0xc000a46060, 0x7fffcc7bc759, 0x8, 0xc002ec2b60)
	/home/runner/work/rac-extract-payload/rac-extract-payload/internal/exports/disk_writer.go:74 +0x516
created by github.com/innosat-mats/rac-extract-payload/internal/exports.DiskCallbackFactory.func1
	/home/runner/work/rac-extract-payload/rac-extract-payload/internal/exports/disk_writer.go:67 +0x1bb

**Comment by OleMartinChristensen** [comment]
Fix if I set ulimit -n 2048
but is there some files that are not closed correctly?

**Comment by joakimmoller** [comment]
How many files matches the `from_xml_202010*.rac` roughly ?

**Comment by OleMartinChristensen** [comment]
37 files, producing around 280 000 images (3 days of data)

**Comment by skymandr** [comment]
Deprecated
