### ISSUE TITLE
Is DigGain /  Gain trunctaion applied in L0?

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/rac-extract-payload#133]
Hi we are looking through the L1 code now before we can send it to you and we found that we are compensating for something called DigGain which we think its the same as Gain truncation. Is this correction allready applied in the L0 processing?

**Comment by joakimmoller** [comment]
@skymandr can you look at it?

**Comment by skymandr** [comment]
@OleMartinChristensen: I have convinced myself that we _don't_ apply any truncation in RAC processing, but simply store the value that is supposed to be used for truncation of the gain. This value should be called `GAIN Truncation` in the `csv`.

**Comment by OleMartinChristensen** [comment]
Yes, I think that makes sense @skymandr. I just got a bit confused with what it actually was (I thought is was the same as WDWMODE, but its FPGA truncation. We will include it in the first step of the L1 processing then.

**Comment by skymandr** [comment]
If you are satisfied that this is investigated, please close the issue, @OleMartinChristensen .
