### ISSUE TITLE
UTC Time needs compensation

### ISSUE THREAD

**Issue by donal-mur** [innosat-mats/rac-extract-payload#135]
Same issue as in level1a/platform: https://github.com/innosat-mats/level1a-platform/issues/3, UTC Time needs 18 sec corr:

> The time in OHB files is time since GPS start - Obs according to IS-OSE-TN-0045_1 Reference Frames for InnoSat ACS.pdf there is a -18 second difference between GPS time and UTC. So the reference time used to compute date time needs to be reduced by 18 sec
> GPSstartime + datetime.timedelta(seconds = -18)
> 
> Found this when comparing GNSS positions with my own calculations

Clarification from @OleMartinChristensen:

>  In rac-extract the nanoseconds is extracted from two fields in the payload data package. This entry (nanoseconds) is correct. But you also convert this into a UTC date (which we have asked for), but in this conversion you assume that the epoch for the nanosecons is some other standard than the GPS time that the satellite uses (either you assume UTC of TIA, I'm not sure).
> 
> However we have checked and the discrepancy is 18 s. i.e. you should subtract 18s from the TMHeaderTime and EXP Date fields.

**Comment by skymandr** [comment]
Plus or minus? Could you flesh out this issue with more information about the problem and what needs doing?

Also, in case this is compensated for in L1 already, won't compensating here as well lead to double compensating..?

**Comment by donal-mur** [comment]
Look at the issue in level1p/platform


On 28 Sep 2022, at 14:39, Andreas Skyman ***@***.******@***.***>> wrote:



Plus or minus? Could you flesh out this issue with more information about the problem and what needs doing?

Also, in case this is compensated for in L1 already, won't compensating here as well lead to double compensating..?

**Comment by skymandr** [comment]
Updated issue. The question of where the correct place to correct for this is remains, however. Unless I'm misstanken, this tool, so far, only extracts data. I don't think any kind of processing or compensation is applied here. Changing that division of responsibilities should, in my opinion, be done with great care.

**Comment by donal-mur** [comment]
If I understand correctly there is a csv file produce with both nanoseconds and UTC the UTC in that file is wrong

**Comment by OleMartinChristensen** [comment]
To clarify. In rac-extract the nanoseconds is extracted from two fields in the payload data package. This entry (nanoseconds) is correct. But you also convert this into a UTC date (which we have asked for), but in this conversion you assume that the epoch for the nanosecons is some other standard than the GPS time that the satellite uses (either you assume UTC of TIA, I'm not sure).

However we have checked and the discrepancy is 18 s. i.e. you should subtract 18s from the TMHeaderTime and EXP Date fields.

**Comment by skymandr** [comment]
I have updated the issue with your clarification, @OleMartinChristensen. Thanks for the input.
