### ISSUE TITLE
Is it possible to extract just one or a few .csv files instead of all seven?

### ISSUE THREAD

**Issue by jonashedin** [innosat-mats/rac-extract-payload#143]
When using rac-extract-payload I get all .csv files and images extracted. If I set option '-skip-images' I don't extract the images and get only the seven .csv files. But is there a way to just extract one or a few .csv files instead of all seven? For example, I would like to extract photometer data and only get the PM.csv file. Can I do that? Or if I for some reason want to extract e.g PM.csv and PWR.csv only, can I do that? /Jonas

**Comment by joakimmoller** [comment]
No, not possible.

 We are going to change the behavior of the rac-extract-payload to output only one parquet-file per rac-file, where all images and data are kept together. Then it would be pretty easy for you to filter out the info you need.

If you prefer the old way you could still use the version of rac-extract-payload you are using now.
