### ISSUE TITLE
Duplicate EXP Nanoseconds for images of same channel

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/rac-extract-payload#150]
During pass 263 we experienced that two of the images had the same time of exposure, though all the other metadata was different. Including TMheadertime. This is an issue either with rac-extract, or in the instrument. Since as a start its easier to debug rac-extract can you please have a look at the raw data and see i this anomaly is present there (hex-dump would be nice), or if rac-extract is the culprit?

**Comment by OleMartinChristensen** [comment]
the data is located here https://chalmersuniversity.box.com/s/joqy8mnir7amelvrwomxd1jm0xzxp62z

**Comment by skymandr** [comment]
> the data is located here https://chalmersuniversity.box.com/s/joqy8mnir7amelvrwomxd1jm0xzxp62z
I get:
![image](https://user-images.githubusercontent.com/358614/203305336-8ae0e249-d909-4b6c-b525-2322b7adaf49.png)

Maybe you could zip it and upload it as an attachment to the issue?

**Comment by OleMartinChristensen** [comment]
[Pass263.zip](https://github.com/innosat-mats/rac-extract-payload/files/10067071/Pass263.zip)

**Comment by OleMartinChristensen** [comment]
attachment added @skymandr

**Comment by joakimmoller** [comment]
Documentation version used for decoding the message:
RAMSES: SPU045-S2:6F
INNOSAT: IS-OSE-ICD-0005:1
Specification: AEZICD002:H

**Comment by skymandr** [comment]
I have investigated and concluded that it is an issue within the RAC-file. This was done by finding the byte representation of the offending timestamps and their respective packages in the RAC file and comparing it to the output of the same from the RAC-extraction program:

![racmap](https://user-images.githubusercontent.com/358614/203611725-35a38c5e-0ed5-4650-a733-f825af33d222.png)

The image is not completely intuitive, but you can see that I have identified headers that correspond to the two packages, followed by (in reverse order to the printout) the representations of `EXPTS` and `EXPTSS`.

Not shown here is that the two images are frames 4 and 5 in the same batch, whatever that means, and that the first has an exposure time (`TEXPMS`) of `60000`, whereas the second has `90000`. One thing we wondered, in relation to this was if it is technically possible to start the exposure at one time, but then read the image buffer at different times, thereby getting two images with the same timestamp. If so, then maybe this is a feature, not a bug? Does anyone know?

**To conclude:** This is not a bug in the `rac` program, but maybe it is not a bug in onboard system either..?

Are you satisfied that this is investigated, @OleMartinChristensen ?

**Comment by OleMartinChristensen** [comment]
thanks you, this is what I wanted to have, I will move on and take the issue to the rest of the team :)

**Comment by joakimmoller** [comment]
# Adding more info about each image:

## First image
![fart09_1353141342056808472_3](https://user-images.githubusercontent.com/22596385/203630571-ed5de347-969f-4811-b33f-5aa54143b34a.png)
``` json
{
    "origin": {
        "name": "fart09",
        "processingTime": "2022-11-23T20:12:27.15778769+01:00"
    },
    "ramsesHeader": {
        "specification": "SPU045-S2:6F",
        "ramsesTime": "2022-11-22T09:41:13.814Z"
    },
    "ramsesTMHeader": {
        "qualityIndicator": 0,
        "lossFlag": 0,
        "vcFrameCounter": 186
    },
    "sourceHeader": {
        "specification": "IS-OSE-ICD-0005:1",
        "spSequenceCount": 7821
    },
    "tmHeader": {
        "tmHeaderTime": "2022-11-22T08:35:24.136779785Z",
        "tmHeaderNanoseconds": 1353141342136779785
    },
    "SID": "",
    "RID": "CCD3",
    "data": {
        "specification": "AEZICD002:I",
        "CCDSEL": 3,
        "EXPNanoseconds": 1353141342056808472,
        "EXPDate": "2022-11-22T08:35:24.056808472Z",
        "WDWMode": "Manual",
        "WDWInputDataWindow": "15..0",
        "WDWOV": 0,
        "JPEGQ": 101,
        "FRAME": 4,
        "NROW": 511,
        "NRBIN": 1,
        "NRSKIP": 0,
        "NCOL": 2047,
        "NCBINFPGAColumns": 1,
        "NCBINCCDColumns": 1,
        "NCSKIP": 0,
        "NFLUSH": 1023,
        "TEXPMS": 60000,
        "GAINMode": "High",
        "GAINTiming": "Faster",
        "GAINTruncation": 0,
        "TEMP": 4228,
        "FBINOV": 0,
        "LBLNK": 287,
        "TBLNK": 293,
        "ZERO": 124,
        "TIMING1": 5149,
        "TIMING2": 518,
        "VERSION": 50,
        "TIMING3": 41987,
        "NBC": 0,
        "BC": []
    }
}
```
## Second image - longer exposure time

![fart11_1353141342056808472_3](https://user-images.githubusercontent.com/22596385/203630578-d4e7c9f4-ab76-44f6-af10-676e6a1f70a8.png)
``` json
{
    "origin": {
        "name": "fart11",
        "processingTime": "2022-11-23T20:12:27.15779289+01:00"
    },
    "ramsesHeader": {
        "specification": "SPU045-S2:6F",
        "ramsesTime": "2022-11-22T09:41:20.673Z"
    },
    "ramsesTMHeader": {
        "qualityIndicator": 0,
        "lossFlag": 0,
        "vcFrameCounter": 77
    },
    "sourceHeader": {
        "specification": "IS-OSE-ICD-0005:1",
        "spSequenceCount": 9992
    },
    "tmHeader": {
        "tmHeaderTime": "2022-11-22T08:36:58.282730103Z",
        "tmHeaderNanoseconds": 1353141436282730103
    },
    "SID": "",
    "RID": "CCD3",
    "data": {
        "specification": "AEZICD002:I",
        "CCDSEL": 3,
        "EXPNanoseconds": 1353141342056808472,
        "EXPDate": "2022-11-22T08:35:24.056808472Z",
        "WDWMode": "Manual",
        "WDWInputDataWindow": "15..0",
        "WDWOV": 0,
        "JPEGQ": 101,
        "FRAME": 5,
        "NROW": 511,
        "NRBIN": 1,
        "NRSKIP": 0,
        "NCOL": 2047,
        "NCBINFPGAColumns": 1,
        "NCBINCCDColumns": 1,
        "NCSKIP": 0,
        "NFLUSH": 1023,
        "TEXPMS": 90000,
        "GAINMode": "High",
        "GAINTiming": "Faster",
        "GAINTruncation": 0,
        "TEMP": 4228,
        "FBINOV": 0,
        "LBLNK": 287,
        "TBLNK": 292,
        "ZERO": 123,
        "TIMING1": 787,
        "TIMING2": 777,
        "VERSION": 50,
        "TIMING3": 259,
        "NBC": 0,
        "BC": []
    }
}
```
