### ISSUE TITLE
How to deal with large messages?

### ISSUE THREAD

**Issue by noreklint** [innosat-mats/rac-extract-payload#163]
When doing a reprocessing (or after recovering from a stop etc), the message from the L0-fetcher may include many rac files. The rac extractor tries to process all of them, which with our standard setup of lambda memory/storage/time will fail due to requiring too much of either/all.

What to do about this?
- Allocate more memory/storage always?
- Remember to increase when doing a reprocessing?
- Redesign?
***
Use a FIFO-queue! send messages to the wueue in order.

**Comment by skymandr** [comment]
I think what we said previously was to batch the reprocessing (manually or automated), but I agree that's a bit crude.

**Comment by noreklint** [comment]
Solved by https://github.com/innosat-mats/level1a-platform/issues/14
