### ISSUE TITLE
some images missing maybe

### ISSUE THREAD

**Issue by donal-mur** [innosat-mats/rac-extract-payload#165]
the version of Mac extract being used by molflowz may be missing images
I only find 3 between 18 och 21 den 5 dec.  OM och Björn säger att det ska vara 8

**Comment by bjornlindr** [comment]
I have also noted that when reading in files from large batches of rac files (unpacked) data seems to be missing.
For example I've tried extracting all of the rac files that we have, then slicing through these for images I want. 
Doing that few images are found. I have found it more reliable to only extract files for relevant days and then search through these.
Could be related

**Comment by joakimmoller** [comment]
Yes, we had some problems with corrupt image data in some rac-files, the data could not be read as 12bit jpeg, so rac-extract just stopped in the middle of execution, causing corrupt output. (less than expected). @skymandr  fixed this inv1.1.1 and patch the old release (v.0.2.8)

Using the dataset in "ops-payload-level1a-v0.2" returns 6 images in the period 2022-12-05T18:00Z--2022-12-05T21:00Z

```python
from pyarrow import fs
import pyarrow.dataset as ds
import boto3
from datetime import datetime, timezone

session = boto3.session.Session(profile_name="mats-read")
credentials = session.get_credentials()

s3 = fs.S3FileSystem(
    secret_key=credentials.secret_key,
    access_key=credentials.access_key,
    region=session.region_name,
    session_token=credentials.token)

dataset = ds.dataset(
    "ops-payload-level1a-v0.2",
    filesystem=s3
)


table = dataset.to_table(
    columns=['EXPDate', 'WDWMode'],
    filter=(
        ds.field('EXPDate') > datetime(2022, 11, 24, 0, 0, tzinfo=timezone.utc)
    ) & (
        ds.field('EXPDate') < datetime(2022, 12, 11, 0, 0, tzinfo=timezone.utc)
    )
)
df = table.to_pandas()
df[(df.index > '2022-12-05T18:00Z') & (df.index < '2022-12-06T00:00Z')]
```

**Comment by skymandr** [comment]
> och Björn säger att det ska vara 8

As @joakimmoller says, we find 6 images in the specified interval. Does that mean 2 are still missing..? @bjornlindr @donal-mur

**Comment by donal-mur** [comment]
Jag läste fel Björn och Olemar sa 6 images
