### ISSUE TITLE
Partition different data based on different timestamps?

### ISSUE THREAD

**Issue by skymandr** [innosat-mats/rac-extract-payload#168]
The processing chain works file-by-file, so that later stages follow the same partitioning scheme as this one, which is based on the source header (`TMHeader`) time. This is probably OK in most cases, but for instance CCD data and PM data have their own timestamps that it would be more convenient to partition by. The difference should not be very large between these times and the source header times, but still.

Should we adapt the partitioning to be on data specific times where available?

**Comment by joakimmoller** [comment]
Andreas says: Bad idea.
