### ISSUE TITLE
Make a filesystem JPEG writer

### ISSUE THREAD

**Issue by local-minimum** [innosat-mats/rac-extract-payload#20]
image data spans over multiple platform packages. Grouping of several packages necessary . Data is encoded in jpeg.

Needs #10

**Comment by skymandr** [comment]
We think this is as easy as reading the correct binary blob and saving it with the correct filename.

**Comment by local-minimum** [comment]
Me too, but need to handle file split over files though so needs to recognize when it should append and when it should start from the beginning.

**Comment by joakimmoller** [comment]
Note that CCDImagePack should be read to the struct as LittleEndian to get the correct values.

Data comes in two different forms when JPEGQ>100 it is raw pixel data, other wise a jpeg file. Better to save everything as a png, need synchronization with #33 ?
