### ISSUE TITLE
Make a filesystem timeseries writer

### ISSUE THREAD

**Issue by local-minimum** [innosat-mats/rac-extract-payload#21]
Given header(s) and payload (PWRReport, HTRReport, CPRUReport (for CRPUA and CPRUB)) write content in a suitable transmission format to a file on disk.

**Comment by joakimmoller** [comment]
Note that #28 is related.

**Comment by local-minimum** [comment]
Are we sure we don't want the data from #26 in the timeseries database too?

**Comment by local-minimum** [comment]
I did a quick check on golang support for influx and there seems to be good support https://github.com/influxdata/influxdb-client-go, but I would argue we would like to use the params constructor pattern in case of an AWS influx solution. That probably means we can't use the same here.

**Comment by local-minimum** [comment]
This has information about json serialization (and after a while about writing custom marshal/unmarshal for things like enums:

https://code.tutsplus.com/tutorials/json-serialization-with-golang--cms-30209

I'm a bit sceptical to json as it will probably use a lot of disk because of repeating keys for each element.

Since we are trying new things, there's also protobuffers: https://pkg.go.dev/mod/google.golang.org/protobuf but I think it will require more of a python user to read such buffers.

We could also make a csv per payload housekeeping type with https://golang.org/pkg/encoding/csv/
It's easy enough to import as sheets to excel or with pandas in python and cross-reference events that happen in various sensors.
