### ISSUE TITLE
Make a time series writer from Platform HK (HDF)

### ISSUE THREAD

**Issue by joakimmoller** [innosat-mats/rac-extract-payload#23]
The innosat platform collects housekeeping data stored in hdf files. Example files available in box.

Read a batch of HK-datafiles to produce a full set of time series data.

**Comment by local-minimum** [comment]
This doesn't sound like an issue for `rac-extract-payload`. Where's that code supposed to go? Is there a task for setting up a new repository and infrastructure around it?

**Comment by local-minimum** [comment]
* Make first PR only setting up repository and CI and such
* Then make PR with content.
