### ISSUE TITLE
Support different ICD versions

### ISSUE THREAD

**Issue by joakimmoller** [innosat-mats/rac-extract-payload#32]
Test data comes with data structure definitions from different specification versions. It would be nice to automatically detect specifications from the dataset but for simplicity a cli option to define what version the data should be decoded with (-v H , --issue H, --aez-issue H) or similar.

**Comment by local-minimum** [comment]
Is it really necessary? Isn't it better to only support version H and have enough test-data for it?

**Comment by joakimmoller** [comment]
After the meeting today it seems like we don't need to support any other version than H (2.6.1)
