### ISSUE TITLE
Something is wrong with github CI

### ISSUE THREAD

**Issue by local-minimum** [innosat-mats/rac-extract-payload#38]
I get an error: 
```
##[error]        heater_regulators_test.go:163: HTR.CSVHeaders() = [HTR1A HTR1B HTR1OD HTR2A HTR2B HTR2OD HTR7A HTR7B HTR7OD HTR8A HTR8B HTR8OD WARNINGS], want [HTR1A HTR1B HTR1OD HTR2A HTR2B HTR2OD HTR7A HTR7B HTR7OD HTR8A HTR8B HTR8OD]
```
on my branch on github, but not on my machine. The error indicates that the tests were actually not run on my branch as it is but rather on how my branch would be when I update against master. This is a rather confusing and annoying behaviour.

**Comment by BengtRydberg** [comment]
Vi använder   

   - name: Check out code into the Go module directory
      uses: actions/checkout@v2

i våran go.yml workflow fil. Det här betyder att din PR mergas med master head, som väl förklarar ditt problem.

https://github.com/actions/checkout/issues/27

"Yes, this is the intended default behavior. The goal is to validate that the pull request will build and test against what it would be merged into. Continuous integration builds need to take into account what they'll be merge into, not the state of the repository when they were created. This prevents you from merging a commit that breaks master but "worked on my machine".

ska gå att använda detta om du bara vill validera din PR 

steps:
- uses: actions/checkout@v1
  with:
    ref: ${{ github.head_ref }} 

Vi kan diskutera på standup imorgon hur vi vill ha det.

**Comment by local-minimum** [comment]
fint, jag tycker det låter fel att köra ci mergat mot master när vi ändå kräver up to date med master på branch.

**Comment by BengtRydberg** [comment]
uppdaterat så vi bygger vid all pushar, och inte nödvändigtvis mergat med master.
