### ISSUE TITLE
Missing CI

### ISSUE THREAD

**Issue by local-minimum** [innosat-mats/rac-extract-payload#49]
CI should run `gopnm` so stuff like:
```
github.com/jbuchbinder/gopnm is not in your go.mod file.
```
doesn't slip through.

It should probably also run `govet`

**Comment by joakimmoller** [comment]
> CI should run `gopnm` so stuff like:

please clarify.

**Comment by local-minimum** [comment]
When I merged master into my branch there appeared problems. One of them was reported by gopnm saying that one of our dependencies wen't correctly handled in `go.mod`.
