### ISSUE TITLE
Handle filenames with spaces

### ISSUE THREAD

**Issue by skymandr** [innosat-mats/rac-extract-payload#54]
When running 
`~/go/bin/rac -output rac-out Payload\ RT_20191023-115059_20191024-125014.rac`
files are created with `'` as part of the filename, _e.g._: 
`'Payload RT_20191023-115059_20191024-125014_PWR.csv'`

Make sure spaces in filenames are handled in a better way, so that the resulting files get filenames that we can handle.

**Comment by skymandr** [comment]
Flagging as invalid - I think this is probably just how `ls` displays it. Someone else could perhaps have a look before closing?

**Comment by local-minimum** [comment]
I don't have any with space in them, but I suggest we just close this and reopen if we know it is a problem / get a user complaint.
