### ISSUE TITLE
CCD Image Pack Data Header: What are the TIMINGs?

### ISSUE THREAD

**Issue by local-minimum** [innosat-mats/rac-extract-payload#79]
There are three timings that comes:

```
TIMING1
TIMING2
VERSION
TIMING3
```
The spec says something about these timings being parts, is that something we should make whole and if so how?

**Comment by joakimmoller** [comment]
@OleMartinChristensen currently we are not parsing these values, we are just reporting them. Should we do something with it?

**Comment by OleMartinChristensen** [comment]
the exact defintiion of the timings are shown in Table 4 of the "Internal Payload ICD" (I just uploaded new version to box now). I think we could extract the correct values, however i'm a bit unsure exactly how to determine wether the values in the header represents 1rt or 2rt values... I think it would be nice to have it, but its a low priority fix I think. 

I will mail KTH and check what they think.

**Comment by skymandr** [comment]
@OleMartinChristensen FYI, I think adding these is a very quick fix on our part, but of course it's your budget. (@local-minimum: shout if you think this is not a trivial addition!)

**Comment by local-minimum** [comment]
If there's a spec and we know what to do it should be easy to fit them in both in the json and csv exports.
