### ISSUE TITLE
CSV from entire directories

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/rac-extract-payload#93]
If I run the code for multiple files, I think it would be preferable to get only one csv file for each variable, rather than one for each variable and input file.

**Comment by local-minimum** [comment]
I'll fix this, but fyi, that implies any pre-existing csvs will be overwritten so if you first run

`rac --project binning2020 myracs/2020binning-part1/*.rac`

And then later get another folder with more racs you want to include in the same project you would have to do:

`rac --project binning2020 myracs/2020binning-part1/*.rac myracs/2020binning-part2/*.rac`

Processing everything from the beginning again.

For the processing pipeline when the satellite is in orbit, we would have to do something like calling each week a project like `cli -project 2021-01 ...`

**Comment by OleMartinChristensen** [comment]
what does the --project do?

**Comment by local-minimum** [comment]
It replaces the old `-output`. If you write to disk it puts it in a directory with that name, if you send data to aws it does something kind of similar.
